### ISSUE TITLE
Update external lecturer

### ISSUE THREAD

**Issue by emdupre** [jbpoline/computational-neuro-week1#5]
Kirstie confirmed she's actually _not_ going to be available this week.

What do folks think of Felix from Calcul Quebec coming to chat about Binder ? cc @jbpoline @pbellec @illdopejake

**Comment by illdopejake** [comment]
Well, on the one hand, he's not exactly *external* the way I was thinking about it. With ISMRM happening, it's possibly a golden opportunity to get a truly external person and actually convince them to come to Montreal since they'll already be here anyway.

On the other hand, it won't be easy to convince an external person to come give a beginner level tutorial on anything unless it's something they already do a lot. Felix would definitely give a good Binder talk. I think, no matter what, it would be beneficial to bring him in, if he's game.

But I still wonder if we could be more ambitious with someone even more "external". The problem is we would have to think of someone... Just thoughts

**Comment by emdupre** [comment]
Closing this as we've identified [Felix](https://twitter.com/cmdntrf) and [Manjari](https://twitter.com/NeuroStats) as our externals for the week !
